# Generated by Django 5.1.6 on 2025-03-02 04:17

import colaboradores.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaboradores',
            fields=[
                ('id_colaborador', models.IntegerField(primary_key=True, serialize=False)),
                ('cpf', models.CharField(max_length=11, validators=[colaboradores.models.validate_cpf], verbose_name='CPF')),
                ('dt_nascimento', models.DateField(verbose_name='Data de nascimento')),
            ],
        ),
    ]
