# Generated by Django 5.1.6 on 2025-03-02 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaboradores',
            name='nome',
            field=models.CharField(default='kaua', max_length=100),
            preserve_default=False,
        ),
    ]
