# Generated by Django 5.1.6 on 2025-03-02 19:53

import colaboradores.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0002_colaboradores_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaboradores',
            name='cpf',
            field=models.CharField(max_length=14, validators=[colaboradores.models.validate_cpf], verbose_name='CPF'),
        ),
    ]
