# Generated by Django 5.1.6 on 2025-03-03 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('areas_tecnologicas', '0001_initial'),
        ('colaboradores', '0004_alter_colaboradores_cpf'),
        ('financiadores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colaboradores.colaboradores')),
            ],
        ),
        migrations.CreateModel(
            name='Projetos',
            fields=[
                ('id_projeto', models.IntegerField(primary_key=True, serialize=False)),
                ('projeto', models.CharField(max_length=100)),
                ('ativo', models.BooleanField()),
                ('inicio_vigencia', models.DateField()),
                ('fim_vigencia', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qtd_membros', models.IntegerField()),
                ('equipe', models.ManyToManyField(related_name='projetos', through='projetos.Equipe', to='colaboradores.colaboradores')),
                ('id_area_tecnologica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='areas_tecnologicas.areastecnologicas')),
                ('id_financiador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financiadores.financiadores')),
            ],
        ),
        migrations.AddField(
            model_name='equipe',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipes', to='projetos.projetos'),
        ),
        migrations.AlterUniqueTogether(
            name='equipe',
            unique_together={('projeto', 'colaborador')},
        ),
    ]
