# Generated by Django 5.1.6 on 2025-03-02 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreasTecnologicas',
            fields=[
                ('id_area_tecnologica', models.IntegerField(primary_key=True, serialize=False)),
                ('area_tecnologica', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
