# Generated by Django 5.1.6 on 2025-03-02 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Financiadores',
            fields=[
                ('id_financiador', models.IntegerField(primary_key=True, serialize=False)),
                ('financiador', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
